# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 528527430b14a60036b33ab1aa191a5b312a5aa2f549a7acccbcb874b40a9c830dc11933aef593cd37f2d662798388b81275abbfc48d66fc362d8b69e7420382

test:
  secret_key_base: d8c72e4b4e0a2074b5ada1278125aa0384ea7bf2abcc61fff4bf07a9aee73d83fab9479252b2e16a5601428c903f6a802b06ec2c089b54d5b00aace94b3ba590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
